version: '3'
services:
    web:
        build: .
        command: python3 /sport247/manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/sport247
        ports:
            - 8000:8000
        depends_on:
            - db
        env_file:
            - .env
    db:
        image: mysql:8.0.29
        restart: always
        command: --default-authentication-plugin=mysql_native_password --mysqlx=0
        environment:
            MYSQL_DATABASE: django_test_db
            MYSQL_USER: root
            MYSQL_PASSWORD: Root@123
            MYSQL_ROOT_PASSWORD: Root@123
        volumes:
            - ".dbdata:/var/lib/mysql"
        ports:
            - '3305:3306'
        env_file:
            - .env